export const LOGIN_REQUEST='LOGIN_REQUEST';
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILURE="LOGIN_FAILURE";

export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAILURE="REGISTER_FAILURE";

export const GET_PROFILE_REQUEST="GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS="GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE="GET_PROFILE_FAILURE";

export const UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE="UPDATE_PROFILE_FAILURE";

export const SEARCH_USER_REQUEST="SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS="SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILURE="SEARCH_USER_FAILURE";

export const LOGOUT_REQUEST="LOGOUT_REQUEST";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAILURE="LOGOUT_FAILURE";

export const CONFIRM_USER_REQUEST="CONFIRM_USER_REQUEST";
export const CONFIRM_USER_SUCCESS="CONFIRM_USER_SUCCESS";
export const CONFIRM_USER_FAILURE="CONFIRM_USER_FAILURE";

export const GET_RECOMENDETIONS_REQUEST="GET_RECOMENDETIONS_REQUEST";
export const GET_RECOMENDETIONS_SUCCESS="GET_RECOMENDETIONS_SUCCESS";
export const GET_RECOMENDETIONS_FAILURE="GET_RECOMENDETIONS_FAILURE";

